### ISSUE TITLE
Does not build on MacOS X with QT5 and SDL2

### ISSUE THREAD

**Issue by PikalaxALT** [pokemon-speedrunning/gambatte-speedrun#1]
Fails earlier when XCode compilers are used (g++: error: unrecognized command line option ‘-Xarch_x86_64’) than when native CLang compilers are used (ld: symbol(s) not found for architecture x86_64).  Tried both QT and SDL flavors.

Parent fork also fails to build in the same environment.

OS X Sierra (10.12) with freshly-installed scons, qt5, and sdl2.

Note that SDL1 support is ending.

**Comment by Dabomstew** [comment]
This almost certainly seems to be either an environment issue or a Qt issue, as nothing in this project's configuration/Makefiles specifies anything to do with processor architecture. Either way, if the parent fork also fails to build, I'm probably not in any position to know how to fix the issue.

On a side note you should focus on getting the gambatte_qt interface compiling - the sdl interface has not been updated to include BIOS support properly for this fork and I intend to just remove it altogether.

**Comment by entrpntr** [comment]
Three years later, we finally have some decent build instructions for macOS, and they even work on at least 2 (!) different development machines. So I think this can be closed.

For posterity, here are the most recently updated Homebrew formulae for qt I could find if developing on an older version of macOS:
* [Yosemite](https://raw.githubusercontent.com/Homebrew/homebrew-core/48421a0c709ea9f204cd41d0e28fcfc5854f0d49/Formula/qt.rb): macOS 10.10, Qt 5.9.1
* [El Capitan](https://raw.githubusercontent.com/Homebrew/homebrew-core/56c500b569c724b049be7ab9e12d9693f85522f9/Formula/qt.rb): macOS 10.11, Qt 5.11.2
* [Sierra](https://raw.githubusercontent.com/Homebrew/homebrew-core/8df3b65f2d7cd6408830df8dd7e99d6f58b3ca29/Formula/qt.rb): macOS 10.12, Qt 5.13.1

No guarantees any of these formulae work, because only macOS 10.13+ have been tested for development. The general idea of finding these commits is cloning homebrew-core and wading through commits that touched `Formula/qt.rb`.

Of course, feel free to open a new issue if any macOS build issues still aren't properly addressed.
